Commit d9e24e8
Shivvvvvvva
Shivvvvvvva
authored
7 minutes ago
·
·
Verified
Update build-apk.yml
main
1 parent 
22b684d
 commit 
d9e24e8
1 file changed

+3
-4
Lines changed: 3 additions & 4 deletions
File tree
Filter files…
.github/workflows
Search within code
 
‎.github/workflows/build-apk.yml‎
+3
-4
Lines changed: 3 additions & 4 deletions
Original file line number	Diff line number	Diff line change
@@ -21,12 +21,11 @@ jobs:

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant permission for Gradle
        run: chmod +x gradlew
        with:
          gradle-version: '8.10.2'

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
0 commit comments
Comments
0
 (0)
Comment
You're not receiving notifications from this thread.
